# Generated by Django 5.0.6 on 2024-06-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_account_holders_user_alter_account_holders_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_holders',
            name='dob',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='account_holders',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
