# Generated by Django 5.0.6 on 2024-06-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_account_holders_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_holders',
            name='account_status',
            field=models.CharField(default='Inactive', max_length=20),
        ),
        migrations.AddField(
            model_name='account_holders',
            name='user_status',
            field=models.CharField(default='Running', max_length=20),
        ),
    ]
