# Generated by Django 5.0.6 on 2024-06-13 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_account_holders_account_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('upi_no', models.CharField(max_length=100)),
                ('account_no', models.CharField(max_length=20)),
                ('current_amt', models.IntegerField()),
                ('pan_no', models.CharField(max_length=20)),
                ('last_login', models.DateTimeField()),
                ('aadhar_no', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_details', to='app.account_holders')),
            ],
        ),
    ]
