# Generated by Django 5.0.6 on 2024-06-14 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_account_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_details', to='app.account_details')),
            ],
        ),
    ]
