# Generated by Django 5.0.6 on 2024-06-14 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_user_inbox_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_inbox',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_inboxes', to='app.account_holders'),
        ),
    ]
