# Generated by Django 5.0.6 on 2024-06-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_user_inbox_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
