# Generated by Django 5.0.6 on 2024-06-15 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_monthlyprofit'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_loan_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('loan_principle_amt', models.IntegerField()),
                ('loan_purpose', models.CharField(max_length=20)),
                ('loan_period', models.IntegerField()),
                ('loan_release_date', models.DateField()),
                ('loan_close_date', models.DateField()),
                ('loan_id', models.CharField(max_length=20)),
                ('loan_intrest_rate', models.IntegerField()),
                ('loan_returing_amt', models.IntegerField()),
                ('loan_fine_amt', models.IntegerField()),
                ('loan_status', models.CharField(choices=[('Running', 'Running'), ('Renewal', 'Renewal'), ('Closed', 'Closed')], max_length=20)),
                ('loan_renewal_times', models.IntegerField()),
                ('loan_refrence_code', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Account_Details', to='app.account_details')),
            ],
        ),
    ]
