# Generated by Django 5.0.6 on 2024-06-15 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_user_loan_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_loan_details',
            new_name='UserLoanDetails',
        ),
    ]
