# Generated by Django 5.0.6 on 2024-06-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_user_loan_details_userloandetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloandetails',
            name='loan_period',
            field=models.CharField(max_length=20),
        ),
    ]
