# Generated by Django 5.0.6 on 2024-06-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_userloandetails_loan_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloandetails',
            name='loan_period',
            field=models.IntegerField(),
        ),
    ]
