# Generated by Django 5.0.6 on 2024-06-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_userloandetails_loan_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloandetails',
            name='loan_fine_amt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userloandetails',
            name='loan_intrest_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userloandetails',
            name='loan_period',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userloandetails',
            name='loan_principle_amt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userloandetails',
            name='loan_returing_amt',
            field=models.FloatField(),
        ),
    ]
