# Generated by Django 5.0.6 on 2024-06-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_userloandetails_loan_fine_amt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloandetails',
            name='loan_status',
            field=models.CharField(choices=[('Running', 'Running'), ('Renewal', 'Renewal'), ('Processing', 'Processing'), ('Hold', 'Hold'), ('Closed', 'Closed')], max_length=20),
        ),
    ]
