# Generated by Django 5.0.6 on 2024-06-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_userloandetails_loan_paid_amt_usertransactiondetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransactiondetails',
            name='transaction_id',
            field=models.CharField(max_length=100),
        ),
    ]
