# Generated by Django 5.0.6 on 2024-06-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_bank_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_wallet',
            name='bank_amount',
            field=models.FloatField(),
        ),
    ]
