# Generated by Django 5.0.6 on 2024-06-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_bank_wallet_bank_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_wallet',
            name='bank_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
