# Generated by Django 5.0.6 on 2024-06-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_bankwallet_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_holders',
            name='photo',
            field=models.TextField(default=''),
        ),
    ]
