# Generated by Django 5.0.6 on 2024-06-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_account_holders_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_holders',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
