# Generated by Django 5.0.6 on 2024-06-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_account_holders_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_holders',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='upload_photo/'),
        ),
    ]
