# Generated by Django 5.0.6 on 2024-06-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_adminmessage_account_holders_message_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixdepositeusers',
            name='fix_deposite_paid_amt',
            field=models.FloatField(default=0.0),
        ),
    ]
