# Generated by Django 5.0.6 on 2024-06-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='Complaint_id',
            new_name='complaint_id',
        ),
        migrations.AddField(
            model_name='complaint',
            name='reply',
            field=models.TextField(default=''),
        ),
    ]
