# Generated by Django 5.0.6 on 2024-06-23 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_userloandetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloandetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Account_Details', to='app.account_details'),
        ),
    ]
