# Generated by Django 5.0.6 on 2024-06-24 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_userloandetails_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertransactiondetails',
            old_name='loan_id',
            new_name='section',
        ),
    ]
