# Generated by Django 5.0.6 on 2024-07-12 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_usertransactiondetails_section_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerListAccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('customer_username', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_account_no', models.IntegerField()),
                ('customer_mobile_no', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_details', to='app.account_details')),
            ],
        ),
    ]
