# Generated by Django 5.0.6 on 2024-07-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_customerlistaccountmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlistaccountmodel',
            name='customer_mobile_no',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='customerlistaccountmodel',
            name='customer_username',
            field=models.CharField(max_length=20),
        ),
    ]
