# Generated by Django 5.0.6 on 2024-07-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_customerlistaccountmodel_customer_mobile_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_inbox',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
