# Generated by Django 5.0.7 on 2024-07-21 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_user_inbox_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATMCardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('cardholder_name', models.CharField(max_length=100)),
                ('expiration_date', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('pin', models.CharField(max_length=4)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_banking_service', models.BooleanField(default=False)),
                ('withdraw_service', models.BooleanField(default=False)),
                ('atm_card_status', models.BooleanField(default=False)),
                ('atm_card_activation', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atm_card_details', to='app.account_details')),
            ],
        ),
    ]
