# Generated by Django 5.0.7 on 2024-07-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_atmcardmodel_account_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atmcardmodel',
            name='balance',
        ),
    ]
