# Generated by Django 5.0.7 on 2024-07-22 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_remove_atmcardmodel_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionCenterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New Action'), ('pending', 'Pending Action'), ('completed', 'Completed Action'), ('block', 'Blocked Action')], max_length=10)),
                ('description', models.CharField(max_length=250)),
                ('action_status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='action_center', to='app.account_details')),
            ],
        ),
    ]
