# Generated by Django 5.0.7 on 2024-07-22 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_actioncentermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioncentermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_center', to='app.account_details'),
        ),
    ]
