# Generated by Django 5.0.7 on 2024-07-22 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_actioncentermodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='actioncentermodel',
            name='expire_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='actioncentermodel',
            name='issue_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
