# Generated by Django 5.0.7 on 2024-07-27 06:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_actioncentermodel_expire_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionSetByOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('otp', models.CharField(max_length=100)),
                ('account_no', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('atm_card_number', models.CharField(max_length=20)),
                ('transaction_status', models.BooleanField(default=False)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expire_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarnsaction_by_otp', to='app.account_details')),
            ],
        ),
    ]
