# Generated by Django 5.0.7 on 2024-07-27 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_transactionsetbyotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atmcardmodel',
            old_name='atm_card_activation',
            new_name='money_transfer_service',
        ),
    ]
