# Generated by Django 5.0.7 on 2024-07-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_rename_atm_card_activation_atmcardmodel_money_transfer_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsetbyotp',
            name='account_no',
            field=models.IntegerField(default=0),
        ),
    ]
