# Generated by Django 5.0.7 on 2024-07-27 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_alter_transactionsetbyotp_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsetbyotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarnsaction_by_otp', to='app.account_details'),
        ),
    ]
