# Generated by Django 5.0.7 on 2024-07-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_alter_transactionsetbyotp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsetbyotp',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='transactionsetbyotp',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
