# Generated by Django 5.0.7 on 2024-07-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_alter_transactionsetbyotp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsetbyotp',
            name='transaction_action',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transactionsetbyotp',
            name='transactionbyotp_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionsetbyotp',
            name='transaction_status',
            field=models.BooleanField(default=True),
        ),
    ]
