# Generated by Django 5.0.7 on 2024-07-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_alter_actioncentermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioncentermodel',
            name='status',
            field=models.CharField(choices=[('new', 'New Action'), ('pending', 'Pending Action'), ('completed', 'Completed Action'), ('incompleted', 'Incompleted Action')], max_length=20),
        ),
    ]
