# Generated by Django 5.0.7 on 2024-08-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_alter_actioncentermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsetbyotp',
            name='expire_date',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactionsetbyotp',
            name='issue_date',
            field=models.BigIntegerField(default=0),
        ),
    ]
