# Generated by Django 5.0.7 on 2025-09-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_loginactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginactivity',
            name='is_active_session',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
