# Generated by Django 5.0.7 on 2025-09-13 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_loginactivity_is_active_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioncentermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_center', to='app.account_holders'),
        ),
    ]
