# Generated by Django 5.0.7 on 2025-09-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_alter_actioncentermodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='actioncentermodel',
            name='subject_code',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
