# Generated by Django 5.0.7 on 2025-09-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_actioncentermodel_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioncentermodel',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actioncentermodel',
            name='issue_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
