# Generated by Django 5.0.7 on 2025-10-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_alter_actioncentermodel_expire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginactivity',
            name='account_status',
            field=models.CharField(choices=[('block', 'Block'), ('logout_forcely', 'Logout'), ('unblock', 'Unblock'), ('running', 'Running'), ('active', 'Active')], default='active', max_length=20),
        ),
    ]
